trainset : 
  dataset: icdar2017
  set: train

testset : 
  dataset: icdar2017
  set: test


log_dir: experiments
logger : wandb
train_label : cluster

# only use when train on color
grayscale : True

data_augmentation : morph

# base lr 5e-4 to 1e-5
optimizer_options: 
  optimizer: sgd 
  base_lr: 0.2  # this should be less 0.001
  wd: 0.0001
  final_lr: 0.001
  warmup_epochs : 2 # Increasing warmup epochs for a smoother start

super_fancy_new_name: test_repository_densenet

model :  
    name : densenet121
    num_clusters : 100
    encoding : netrvlad

train_options: 
  epochs: 50 
  batch_size: 512                               
  callback : early_stopping
  callback_patience : 8

  loss : triplet  
  margin : 0.1
  sampler_m : 16
  length_before_new_iter: 512000

eval_options : 
    pca_dim : 400
    gmp_alpha : 100

test_batch_size: 512
        